### ISSUE TITLE
项目运行页面错乱

### ISSUE THREAD

**Issue by sanzhixiaoxia** [HarryReidx/chatgpt-java#1]
![image](https://user-images.githubusercontent.com/69310120/226824148-1d298471-49ed-4500-a7b6-593e49114038.png)

**Comment by HarryReidx** [comment]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/52063790/227076927-691766b3-6a75-4ffe-8657-af9014e03398.png">
我这里没问题
建议使用google浏览器，尝试
1.调整浏览器缩放为百分百，win快捷键ctrl+0，manc快捷键command+0 
2.清一下浏览器缓存
